### ISSUE TITLE
Number String breaks the addon

### ISSUE THREAD

**Issue by MinecraftNight4** [cooffeeRequired/skJson#9]
```
on load:
	set {_json} to json from string "{'data_1': 'output_1'}"
	send "BUILD 1:" to console
	send {_json} with pretty print to console
	#
	set {_string} to "32458967213421348712348"
	append "output" with key "arg-1" as nested object "%{_string}%" to {_json}
	send "BUILD 2:" to console
	send {_json} with pretty print to console
```

When a string only contains NUMBERS, it is converted to an INTEGER. Apparently this causes an error when trying to use it on KEYS or NESTED OBJECTS.

**Comment by cooffeeRequired** [comment]
Hi thanks to a good example I managed to replicate this, this is due to the fact that in the old parser there were "thousand" if else checks, in the new one it relies on length and type. Thus this is what happens, fixing the error is literally a matter of seconds. in the next release it will be fixed.
